# EDA readings

Read through the following articles:

[Stats distributions](https://www.research.autodesk.com/publications/same-stats-different-graphs/) describes how by only knowing statistical properties we may be making inaccurate assumptions of what our data actually looks like visually. 

[Implications behind visualizations](https://callingbullshit.org/case_studies/case_study_track_records.html) (excusing the explicit language) has loads of examples of how biases can creep into our data insights. This article shows how we can initially interpret visualizations, and perhaps how to start questioning if the visualization is telling the story we think it is.

[Using LLMs to storyboard](https://pudding.cool/2024/07/ai/) goes through the process of how a data-driven story is created at The Pudding, but using an LLM. This article is a great way to understand how data-driven stories are put together, and how good (or not so good) LLMs are at replicating tasks associated with the design and implementation process.

[ggplot vs plotnine](https://blog.tidy-intelligence.com/posts/ggplot2-vs-plotnine/) compares the graphing power of R's ggplot to Python's plotnine (R wrapper for ggplot). Useful for those who have experience with creating visualizations in R, or for those who are unimpressed by matplotlib's capabilities. Only read if you have a background using R. The following cheatsheets may be helpful for your reference: [data storytelling](../files/data_storytelling.pdf), [data visualizations](../files/data_visualizations.pdf.pdf), [matplotlib](../files/matplotlib.pdf.pdf), [plotly](../files/plotly.pdf.pdf), [seaborn](../files/seaborn.pdf.pdf).