The following standards will be assessed on the CLS quiz:

## ALG-CLS

You should be able to:

- Define the unsupervised learning approach and identify it's associated algorithms
- Explain these algorithms and their associated terms to a non-technical audience
- Identify when to use various unsupervised algorithms


## EVL-CLS

You should be able to:

- Interpret clustering results and identify which clusters are related to ground truths
- Calculate and interpret silhouette coefficients
- Define intra vs inter cluster and when to use these types of calculations
- Interpret cluster evaluation charts

## Study Tips

Review the lecture slides, workbooks, homework assignments, and the associated lab.  
Quiz questions are similar (though not identical) to the types of questions covered in these materials.
You should be able to use appropriate terminology and apply the concepts covered in class to a variety of new scenarios.

The primary goal of each quiz is to give you an opportunity to apply concepts with clear and well-explained reasoning.  
Quizzes are also a valuable opportunity to receive feedback on your reasoning skills.  


## Formulas given

$\text{Silhouette coefficient} = \frac{b-a}{max(a,b)}$
$\text{Euclidean distance} = \sqrt{(x_2 - x_1)^2+ (y_2 - y_1)^2}$




